### ISSUE TITLE
Some information

### ISSUE THREAD

**Issue by Angelk90** [DushyantMainwal/VideoPlayerDemo#1]
Hi @DushyantMainwal: I saw your videos. Can I ask you some questions?

**Comment by DushyantMainwal** [comment]
Yeah, go ahead!

**Comment by Angelk90** [comment]
@DushyantMainwal : Is the video player the one you made in the "ultimate player" playstore? It's a pity you did not continue the tutorial I was interested in understanding how you did certain things. :(

**Comment by DushyantMainwal** [comment]
@Angelk90 No, it's not. It's just a simple video player where I use SurfaceVIew and MediaPlayer to play video. Whereas in "Ultimate Player" I use Vlc sdk for playing video files.

If you have no further queries, can I close this issue?

**Comment by DushyantMainwal** [comment]
@Angelk90 Here, I used this library in "Ultimate Player":

https://github.com/mrmaffen/vlc-android-sdk
